name: "Run Unit Tests"
description: "Runs unit tests using Gradle"
runs:
  using: "composite"
  steps:
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest
      shell: bash

    - name: Archive test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: app/build/reports/tests/testDebugUnitTest/