name: Hello World Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message'
        required: true
        type: string

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Say Hello

        run: echo "Hello, world!" ${{ inputs.message }}
